### ISSUE TITLE
Problems importing sav files

### ISSUE THREAD

**Issue by juanpide** [Stan125/GREA#16] opened 2016-07-18 11:59 UTC
I've been trying GREA.
It works well with csv files,
but when importing SPSS SAV files I can't get the preview and when I press "Done" I get this error:

> Listening on http://127.0.0.1:5670
> 1. Wrong options for generating df, or
> 2. Outcome is not a df (for Excel and SPSS reader functions)

Though, if I use haven or foreign to import it it works well.

**Comment by Stan125** [comment] 2016-07-18 12:34
Hi there, 
Thanks for the remark. Could you send me the file that you used?
Regards,
Stani

**Comment by juanpide** [comment] 2016-07-18 14:57
Hi,
How should I send it?. By email or a public service such as zippyshare?

**Comment by Stan125** [comment] 2016-07-18 15:00
you can send it to me at: "stanislaus at stadlmann dot cm" (not com).

**Comment by juanpide** [comment] 2016-07-18 15:17
Sent

**Comment by Stan125** [comment] 2016-07-18 15:31
I didn't have a problem while importing this file!
![bildschirmfoto 2016-07-18 um 17 29 31](https://cloud.githubusercontent.com/assets/17404160/16920290/57feb2be-4d0d-11e6-96f6-cdf75a5b1642.png)

**Comment by juanpide** [comment] 2016-07-18 17:19
OK, thanks, I'll check it.

**Comment by Stan125** [comment] 2016-07-19 08:50
Hi there, I'mma close this issue. Just write here if the issue is not resolved.

**Closed as completed by Stan125** 2016-07-19 08:50 UTC

**Comment by jtruffa** [comment] 2016-07-19 21:50
Hello, nice work with GREA.

Trying to open a xlsm and didn´t work. Does it work for any Excel type worksheet?

Thanks,

**Comment by Stan125** [comment] 2016-07-19 22:03
I'm afraid only .xls and .xlsx work. Maybe just save it as .xlsx?

**Comment by jtruffa** [comment] 2016-07-20 13:20
Yes, it worked. 

Any chance to make (resize) window bigger? Have a huge spreadsheet.

Again: Great work!

**Comment by Stan125** [comment] 2016-07-20 13:32
Great! There should be a scroll bar somewhere...

**Comment by jtruffa** [comment] 2016-07-20 17:43
Yes, there is. But for huge excel spreadsheets maybe the bigger windows is much useful.

Looks like rio is having trouble to open excel 97 format, concerning sheet number (which parameter). Xlsx works just fine. 
Any news about that?

**Comment by Stan125** [comment] 2016-07-20 20:10
Hmmm... Maybe open an issue over [here](https://github.com/leeper/rio) if you can reproduce the problems with `rio::import()`.
